# Generated by Django 4.0.8 on 2022-12-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('hotel_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('hotel_name', models.CharField(max_length=25)),
                ('hotel_description', models.TextField(default=models.CharField(max_length=25))),
                ('hotel_city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('room_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=20)),
                ('room_capacity', models.IntegerField(max_length=4)),
                ('room_price', models.IntegerField(max_length=7)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='mysite.hotelmodel')),
            ],
        ),
    ]
