# Generated by Django 4.0.8 on 2022-12-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_roommodel_room_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmodel',
            name='hotel_image1',
            field=models.ImageField(blank=True, upload_to='mysite/hotels'),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='room_description',
            field=models.TextField(default=models.CharField(max_length=20)),
        ),
    ]
