# Generated by Django 4.0.8 on 2022-12-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_hotelmodel_hotel_image1_roommodel_room_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelModel',
            new_name='Hotel',
        ),
        migrations.RenameModel(
            old_name='RoomModel',
            new_name='Room',
        ),
    ]
