# Generated by Django 4.0.8 on 2022-12-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_hotel_hotel_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_image2',
            field=models.ImageField(blank=True, upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_image3',
            field=models.ImageField(blank=True, upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_image4',
            field=models.ImageField(blank=True, upload_to='hotels'),
        ),
    ]
