# Generated by Django 4.0.8 on 2022-12-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_room_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_image1',
            field=models.ImageField(blank=True, upload_to='static/mysite/hotels'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_image2',
            field=models.ImageField(blank=True, upload_to='static/mysite/hotels'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_image3',
            field=models.ImageField(blank=True, upload_to='static/mysite/hotels'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_image4',
            field=models.ImageField(blank=True, upload_to='static/mysite/hotels'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=models.ImageField(blank=True, upload_to='static/mysite/rooms'),
        ),
    ]
