# Generated by Django 4.0.8 on 2022-12-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_room_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
