# Generated by Django 4.0.8 on 2022-12-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_alter_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
