# Generated by Django 4.0.8 on 2022-12-17 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_booking_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='nights',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='mysite.room', unique=True),
        ),
    ]
