# Generated by Django 4.0.8 on 2022-12-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_booking_nights_alter_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image1',
            field=models.ImageField(blank=True, upload_to='mysite/hotels'),
        ),
    ]
