# Generated by Django 4.0.8 on 2022-12-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_alter_hotel_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image1',
            field=models.ImageField(blank=True, upload_to='static/mysite/hotels'),
        ),
    ]
