# Generated by Django 4.0.8 on 2022-12-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_hotel_small_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='small_description',
            field=models.TextField(default=models.CharField(max_length=20)),
        ),
    ]
