# Generated by Django 4.0.8 on 2022-12-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_room_small_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image5',
            field=models.ImageField(blank=True, upload_to='static/mysite/hotels'),
        ),
    ]
