# Generated by Django 4.0.8 on 2023-01-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_alter_booking_id_alter_booking_nights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='facilities',
            field=models.TextField(default='Lorum Ipsum'),
        ),
    ]
