# Generated by Django 4.0.8 on 2023-01-10 06:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0031_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 10, 6, 7, 5, 742443, tzinfo=utc)),
        ),
    ]
